LayoutProcessAdmin/Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LayoutProcessAdmin.Models;
using LayoutProcessAdmin.Models.Areas;

namespace LayoutProcessAdmin.Controllers
{
    public class AreasController : Controller
    {
        private LayoutProcessContext db = new LayoutProcessContext();

        // GET: Areas
        public ActionResult Index()
        {
            return View(db.Areas.ToList());
        }

        // GET: Areas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = db.Areas.Find(id);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // GET: Areas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Areas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "int_IdArea,chr_Clave,Name,Description")] Area area)
        {
            if (ModelState.IsValid)
            {
                db.Areas.Add(area);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(area);
        }

        // GET: Areas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = db.Areas.Find(id);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // POST: Areas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "int_IdArea,chr_Clave,Name,Description")] Area area)
        {
            if (ModelState.IsValid)
            {
                db.Entry(area).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(area);
        }

        // GET: Areas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = db.Areas.Find(id);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // POST: Areas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Area area = db.Areas.Find(id);
            db.Areas.Remove(area);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LayoutProcessAdmin/Controllers/AuditsController.cs
using LayoutProcessAdmin.Models;
using LayoutProcessAdmin.Models.Account;
using LayoutProcessAdmin.Models.Auditing;
using LayoutProcessAdmin.Models.Checking;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LayoutProcessAdmin.Controllers
{
    public class AuditsController : Controller
    {
        private LayoutProcessContext db = new LayoutProcessContext();

        // GET: Audits
        public async Task<ActionResult> Index()
        {
            return View(await db.Audits.ToListAsync());
        }

        // GET: Audits/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Audit audit = await db.Audits.Include(x => x.AuditConfigs).SingleOrDefaultAsync(x => x.int_IdAudit == id);
            if (audit == null)
            {
                return HttpNotFound();
            }
            return View(audit);
        }

        // GET: Audits/Create
        public ActionResult Create()
        {
            ViewBag.ListUsers = GetUsersDropDown(null);
            ViewBag.AuditTypes = GetAuditTypes();
            ViewBag.Areas = GetAreas(-1);
            ViewBag.MyChecklists = GetMyChecklists(null);
            return View();
        }

        // POST: Audits/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Create([Bind(Include = "int_IdAudit,chr_Name,chr_Description,int_Type,bit_Activo")] Audit audit)
        {
            var existAudit = await db.Audits.SingleOrDefaultAsync(x => x.chr_Name == audit.chr_Name);

            if (existAudit != null)
                ModelState.AddModelError(string.Empty, "The audit Name already exists.");

            try
            {
                if (ModelState.IsValid)
                {
                    db.Audits.Add(audit);
                    await db.SaveChangesAsync();
                    return Json(new { success = true, data = new { auditId = audit.int_IdAudit } });
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.ToString());
            }
            
            return Json(new { success = false, messagge = ModelState.Values.Where(x => x.Errors.Count > 0).Select(x => x.Errors[0].ErrorMessage).ToList() });
        }

        // GET: Audits/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Audit audit = await db.Audits.FindAsync(id);
            if (audit == null)
            {
                return HttpNotFound();
            }
            return View(audit);
        }

        // POST: Audits/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "int_IdAudit,chr_Name,chr_Description,int_Type")] Audit audit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(audit).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(audit);
        }

        // POST: Audits/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int id)
        {
            Audit audit = await db.Audits.FindAsync(id);
            db.Audits.Remove(audit);
            await db.SaveChangesAsync();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        List<SelectListItem> GetAuditTypes(string selectedType = "-1")
        {
            return new List<SelectListItem>()
            {
                new SelectListItem()
                {
                    Text = "Auditoria",
                    Value = "0",
                    Selected = (selectedType == "0") ? true : false
                },
                new SelectListItem()
                {
                    Text = "Encuesta",
                    Value = "1",
                    Selected = (selectedType == "0") ? true : false
                }
            };
        }

        List<SelectListItem> GetUsersDropDown(List<UsersAudits> users)
        {
            var list = db.Users.ToList();
            var listado = new List<SelectListItem>();

            foreach (var item in list)
            {
                listado.Add(new SelectListItem()
                {
                    Text = item.chr_Name + " " + item.chr_LastName,
                    Value = item.int_IdUser.ToString(),
                    Selected = IsUserSelected(item.int_IdUser, users)
                });
            }

            return listado;
        }

        bool IsUserSelected(int idUser, List<UsersAudits> users)
        {
            if (users == null)
                return false;

            foreach (var user in users)
                if (user.User.int_IdUser == idUser)
                    return true;

            return false;
        }

        List<SelectListItem> GetAreas(int idArea)
        {
            var areas = db.Areas;
            var areasList = new List<SelectListItem>();

            foreach (var area in areas)
                areasList.Add(new SelectListItem()
                {
                    Text = area.Name,
                    Value = area.int_IdArea.ToString(),
                    Selected = (area.int_IdArea == idArea) ? true : false
                });

            return areasList;
        }

        List<SelectListItem> GetMyChecklists(List<Checklist> checklistsSelected)
        {
            var checkLists = new List<SelectListItem>();
            var user = (User)Session["User"];

            var myChecklists = db.Checklists.Where(x => x.int_Owner.int_IdUser == user.int_IdUser).ToList();

            foreach (var checklist in myChecklists)
                checkLists.Add(new SelectListItem() {
                    Text = checklist.chr_Name,
                    Value = checklist.int_IdList.ToString(),
                    Selected = ChecklistsIsSelected(checklist, checklistsSelected)
                });
            
            return checkLists;
        }

        bool ChecklistsIsSelected(Checklist checklist, List<Checklist> checklistsSelected)
        {
            if (checklistsSelected == null)
                return false;

            foreach(var check in checklistsSelected)
                if (check.int_IdList == checklist.int_IdList)
                    return true;

            return false;
        }


        [HttpGet]
        public JsonResult GetSelectedDays(int period)
        {
            try
            {
                var result = db.Periods.Find(period);

                string[] days = new string[10];

                days[0] = (result.bit_Sun) ? "su" : "";
                days[1] = (result.bit_Mon) ? "mo" : "";
                days[2] = (result.bit_Tue) ? "tu" : "";
                days[3] = (result.bit_Wed) ? "we" : "";
                days[4] = (result.bit_Thu) ? "th" : "";
                days[5] = (result.bit_Sun) ? "fr" : "";
                days[6] = (result.bit_Sun) ? "su" : "";

                return Json(new { Success = true, Result = days }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { Success = false, Messagge = e.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        //[HttpGet]
        //public JsonResult GetSelectedArea(int checklist)
        //{
        //    try
        //    {
        //        var check = db.Audits.Include(x => x.Area.SingleOrDefault(x => x.int_IdList == checklist);
        //        return Json(new { Success = true, Result = check.Area.int_IdArea }, JsonRequestBehavior.AllowGet);
        //    }
        //    catch (Exception e)
        //    {
        //        return Json(new { Success = false, Messagge = e.ToString() }, JsonRequestBehavior.AllowGet);
        //    }

        //}
    }
}

LayoutProcessAdmin/Controllers/RolesController.cs
using LayoutProcessAdmin.Models;
using LayoutProcessAdmin.Models.Account;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace LayoutProcessAdmin.Controllers
{
    public class RolesController : Controller
    {
        private LayoutProcessContext db = new LayoutProcessContext();

        // GET: Roles
        public ActionResult Index()
        {
            User user = (User)Session["User"];

            if (user == null)
                return RedirectToAction("Login", "Users");

            if (!user.UserRoles[0].int_LpaRole.bit_ManageUsers)
                return RedirectToAction("NoPermission", "Home", new { module = "Users Managment" });
            return View(db.LpaRoles.ToList());
        }

        // GET: Roles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.LpaRoles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "int_IdRole,chr_Name,chr_Description,bit_ManageUsers,bit_ManageGlobalUsers,bit_ManageChecklist,bit_FillChecklists")] Role role)
        {
            if (ModelState.IsValid)
            {
                db.LpaRoles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int? id)
        {
            User user = (User)Session["User"];

            if (user == null)
                return RedirectToAction("Login", "Users");

            if (!user.UserRoles[0].int_LpaRole.bit_ManageUsers)
                return RedirectToAction("NoPermission", "Home", new { module = "Users Managment" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.LpaRoles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "int_IdRole,chr_Name,chr_Description,bit_ManageUsers,bit_ManageGlobalUsers,bit_ManageChecklist,bit_FillChecklists")] Role role)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(role).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (System.Exception e)
                {
                    return View(e);
                }
            }
            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var roles = db.LpaRoles.Include(x => x.UserRoles).Where(x => x.int_IdRole == id).ToList();

            if(roles[0].UserRoles.Count > 0)
                db.UserRoles.Remove(roles[0].UserRoles[0]); 
            db.LpaRoles.Remove(roles[0]);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LayoutProcessAdmin/Views/Shared/_Footer.cshtml
<footer>
    <div style="margin: 10px;">
        <div class="row">
            <div class="col-lg-6 offset-lg-2 col-md-12 offset-md-0">
                <span class="text-white" style="font-size: 28px;">Layout Process Administrator</span><br /><br />
                <p class="text-white" style="font-size: 12px;">
                    Support: <a class="text-white" href="mailto:desarrollo@calisis.com?Subject=Support%20Help">desarrollo@calisis.com</a><br />
                    Marketing: <a class="text-white" href="mailto:ventas@calisis.com?Subject=Support%20Help">ventas@calisis.com</a><br /> <br /><br />
                </p>
            </div>
            <div class="col-lg-3 col-md-12">
                <div class="row">
                    <div class="col-4 text-center">
                        <img class="img-thumbnail rounded" src="~/Images/calisis.png" alt="Calisis" style="margin-right:auto;margin-left:auto;" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <span class="text-white">© @DateTime.Now.Year </span> <a class="text-white" href="http://www.calisis.com/">Calisis - Calidad y Sistemas.</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

LayoutProcessAdmin/Views/Shared/_Layout.cshtml
@{ 
    var user = (LayoutProcessAdmin.Models.Account.User) Session["User"];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - ListLayer</title>

    <!-- Favicon -->
    <link rel="shortcut icon" src="@Url.Content("~/favicon.ico")" />

    <!-- Bootstrap CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Font Awesome CSS -->
    <link href="~/Content/font-awesome/css/all.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="~/Content/css/style.css" rel="stylesheet" />

    @RenderSection("css", required: false)

</head>

<body class="adminbody">

    <div id="main">

        <!-- top bar navigation -->
        <div class="headerbar">

            <!-- LOGO -->
            <div class="headerbar-left" style="background-color:#00264d;">
                <a href="@Url.Action("Index", "Home")" class="logo">
                    <img src="@Url.Content("~/Images/layers.png")" alt="logo" /> <span>ListLayer</span>
                </a>
            </div>

            <nav class="navbar-custom" style="background-color:#00264d;">
                <ul class="list-inline float-right mb-0">
                    <li class="list-inline-item dropdown notif">
                        <a class="nav-link dropdown-toggle nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                            Welcome @user.chr_Name !
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown ">

                            <a href="#" class="dropdown-item notify-item">
                                <i class="fa fa-user"></i> <span>BOM</span>
                            </a>

                            <a href="~/Applications/BOM/" class="dropdown-item notify-item">
                                <i class="fa fa-user"></i> <span>LPA</span>
                            </a>

                            <hr />

                            <a href="@Url.Action("Logout", "Users")" class="dropdown-item notify-item" role="button">
                                <i class="fa fa-power-off"></i> <span>Logout</span>
                            </a>

                        </div>
                    </li>
                </ul>

                <ul class="list-inline menu-left mb-0">
                    <li class="float-left">
                        <button class="button-menu-mobile open-left" id="SideBarToggle">
                            <i class="fa fa-fw fa-bars"></i>
                        </button>
                    </li>
                </ul>
            </nav>

        </div>
        <!-- End Navigation -->
        <!-- Left Sidebar -->
        <div class="left main-sidebar">

            <div class="sidebar-inner leftscroll">

                <div id="sidebar-menu">

                    <ul>
                        <li class="submenu">
                            <a href="@Url.Action("Index", "Home")"><i class="fas fa-home"></i><span> Inicio </span> </a>
                        </li>

                        @if (user.UserRoles[0].int_LpaRole.bit_ManageChecklist)
                        {
                            <li class="submenu">
                                <a href="#"><i class="fas fa-clipboard-check"></i><span> Checklists </span> <i class="fas fa-angle-right menu-arrow"></i></a>
                                <ul class="list-unstyled">
                                    <li><a href="@Url.Action("Create", "Checklists")">Create</a></li>
                                    <li><a href="@Url.Action("Index", "Checklists")">My checklists</a></li>
                                </ul>
                            </li>
                        }

                        @*@if (user.UserRoles[0].int_LpaRole.bit_ManageAudits)
                        {*@
                            <li class="submenu">
                                <a href="#"><i class="fas fa-file-invoice"></i><span> Audits </span> <i class="fas fa-angle-right menu-arrow"></i></a>
                                <ul class="list-unstyled">
                                    <li><a href="@Url.Action("Index", "Audits")">My Audits</a></li>
                                    <li><a href="@Url.Action("Index", "Areas")">Areas</a></li>
                                </ul>
                            </li>
                        @*}*@

                        @if (user.UserRoles[0].int_LpaRole.bit_ManageUsers)
                        {
                            <li class="submenu">
                                <a href="#"><i class="fas fa-address-book"></i><span>Accounts</span> <i class="fas fa-angle-right menu-arrow"></i></a>
                                <ul class="list-unstyled">
                                    <li><a href="@Url.Action("Index", "Users")">Users</a></li>
                                    <li><a href="@Url.Action("Index", "Roles")">Roles</a></li>
                                </ul>
                            </li>
                        }

                    </ul>

                    <div class="clearfix"></div>

                </div>

                <div class="clearfix"></div>

            </div>

        </div>
        <!-- End Sidebar -->

        <div class="content-page">

            <!-- Start content -->
            <div class="content">

                <div class="container-fluid">
                    @RenderBody()
                </div>

            </div>
            <!-- END content -->

        </div>
        <!-- END content-page -->

        <footer class="footer">
            <span class="text-right">
                Copyright <a target="_blank" href="http://www.calisis.com">http://www.calisis.com</a> &reg;
            </span>
        </footer>

    </div>
    <!-- END main -->


    <script src="~/Scripts/Plugins/js/modernizr.min.js"></script>
    <script src="~/Scripts/Plugins/js/jquery.min.js"></script>
    <script src="~/Scripts/Plugins/js/moment.min.js"></script>

    <script src="~/Scripts/Plugins/js/popper.min.js"></script>
    <script src="~/Scripts/Plugins/js/bootstrap.min.js"></script>

    <script src="~/Scripts/Plugins/js/detect.js"></script>
    <script src="~/Scripts/Plugins/js/fastclick.js"></script>
    <script src="~/Scripts/Plugins/js/jquery.blockUI.js"></script>
    <script src="~/Scripts/Plugins/js/jquery.nicescroll.js"></script>

    <!-- App js -->
    <script src="~/Scripts/Plugins/js/pikeadmin.js"></script>

    <script>
        $(function () {
            $('#SideBarToggle').trigger('click');
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>