LayoutProcessAdmin/Models/Checking/Checklist.cs
using LayoutProcessAdmin.Models.Account;
using LayoutProcessAdmin.Models.Auditing;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace LayoutProcessAdmin.Models.Checking
{
    [Table("Tbl_Checklist")]
    [DataContract(IsReference = true)]
    public class Checklist
    {
        [Key]
        public int int_IdList { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Code")]
        [Index(IsUnique = true)]
        [RegularExpression(@"^\S*$", ErrorMessage = "No white space allowed in code field.")]
        public string chr_Clave { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string chr_Name { get; set; }

        [StringLength(350)]
        [Display(Name = "Description")]
        public string chr_Description { get; set; }
        
        public User int_Owner { get; set; }

        public List<Question> Questions { get; set; }

        public List<AuditConfig> AuditConfigs { get; set; }
    }
}

LayoutProcessAdmin/Controllers/ChecklistsController.cs
using LayoutProcessAdmin.Models;
using LayoutProcessAdmin.Models.Account;
using LayoutProcessAdmin.Models.Checking;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LayoutProcessAdmin.Controllers
{
    public class ChecklistsController : Controller
    {
        private LayoutProcessContext db = new LayoutProcessContext();

        // GET: Checklists
        public ActionResult Index()
        {
            User user = (User)Session["User"];

            if (user == null)
                return RedirectToAction("Login", "Users");

            if (!user.UserRoles[0].int_LpaRole.bit_ManageChecklist)
                return RedirectToAction("NoPermission", "Home", new { module = "Checklists Managment" });

            var myChecklists = db.Checklists.Include(x=>x.Questions).Where(x => x.int_Owner.int_IdUser == user.int_IdUser).ToList();

            return View(myChecklists);
        }

        // GET: Checklists/Attend/5
        public ActionResult Attend(int? id)
        {
            User user = (User)Session["User"];
            
            if (user == null)
                return RedirectToAction("Login", "Users");

            if (!user.UserRoles[0].int_LpaRole.bit_ManageChecklist)
                return RedirectToAction("NoPermission", "Home", new { module = "Checklists Managment" });
            
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var evento = db.Events.Include(x=>x.AuditConfig).FirstOrDefault(x=>x.int_IdEvent == id);

            //var auditConfig = db.AuditConfigs.Include(x=>x.Checklist).FirstOrDefault(x => x.int_IdAuditConfig == evento.AuditConfig.int_IdAuditConfig);

            //var checklist = db.Checklists.Include(x => x.Questions).FirstOrDefault(x => x.int_IdList == auditConfig.Checklist.int_IdList);

            //var answers = db.Answers.Where(x => x.int_Question.int_Checklist.int_IdList == checklist.int_IdList).ToList();

            return View(evento);
        }

        public JsonResult GetChecklist(int? id)
        {
            var config = db.AuditConfigs.Include(x => x.Checklist).Where(x => x.int_IdAuditConfig == id).First();

            config.Checklist.AuditConfigs = null;

            return Json(new { success = true, data = config.Checklist}, JsonRequestBehavior.AllowGet);
        }

        // GET: Checklists/Create
        public ActionResult Create()
        {
            User user = (User)Session["User"];

            if (user == null)
                return RedirectToAction("Login", "Users");

            if (!user.UserRoles[0].int_LpaRole.bit_ManageChecklist)
                return RedirectToAction("NoPermission", "Home", new { module = "Checklists Managment" });

            //ViewBag.CurrentUser = user;
            //ViewBag.Users = GetUsersDropDown(null);
            //ViewBag.Areas = GetAreas(-1);

            return View();
        }

        

        // POST: Checklists/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create([Bind(Include = "int_IdList,chr_Clave,chr_Name,chr_Description,bit_Activo, Days, SelectedPeriod, SelectedUsers,int_Area, int_Owner")] Checklist checklist)
        {
            try
            {
                //if (checklist.SelectedUsers == null)
                //    ModelState.AddModelError(string.Empty, "You have to choose at least one user to answer this checklist.");

                //if(checklist.Days == null)
                //    ModelState.AddModelError(string.Empty, "Select at least one day from the week.");

                //if(checklist.SelectedPeriod == null)
                //    ModelState.AddModelError(string.Empty, "Select the period for the checklist.");


                if (ModelState.IsValid)
                {
                    var existChl = db.Checklists.Where(x => x.chr_Clave == checklist.chr_Clave).ToList();

                    if (existChl.Count > 0)
                        return Json(-10);
                    else
                    {
                        //foreach (var item in checklist.SelectedUsers)
                        //{
                        //    db.UsersChecklists.Add(new UsersChecklist()
                        //    {
                        //        Checklist = checklist,
                        //        User = db.Users.Find(item)
                        //    });
                        //}

                        //checklist.Area = db.Areas.Find(checklist.int_Area);

                        User user = (User)Session["User"];
                        checklist.int_Owner = db.Users.Find(user.int_IdUser);

                        //var period = new Period()
                        //{
                        //    bit_Sun = FindSelectedDay(checklist.Days, "su"),
                        //    bit_Mon = FindSelectedDay(checklist.Days, "mo"),
                        //    bit_Tue = FindSelectedDay(checklist.Days, "tu"),
                        //    bit_Wed = FindSelectedDay(checklist.Days, "we"),
                        //    bit_Thu = FindSelectedDay(checklist.Days, "th"),
                        //    bit_Fri = FindSelectedDay(checklist.Days, "fr"),
                        //    bit_Sat = FindSelectedDay(checklist.Days, "sa"),
                        //    chr_RepeatPeriod = checklist.SelectedPeriod
                        //};

                        //checklist.int_Period = period;
                    
                        //db.Periods.Add(period);
                        db.Checklists.Add(checklist);
                        db.SaveChanges();
                    }

                    return Json(checklist.int_IdList);
                }
                else
                {
                    var errorMessagge = ModelState.Values.Where(x => x.Errors.Count > 0).Select(x => x.Errors[0].ErrorMessage).ToList();
                    return Json(errorMessagge);
                }
            }
            catch (DbEntityValidationException e)
            {
                StringBuilder sb = new StringBuilder();

                foreach (var failure in e.EntityValidationErrors)
                {
                    sb.AppendFormat("{0} failed validation\n", failure.Entry.Entity.GetType());
                    foreach (var error in failure.ValidationErrors)
                    {
                        sb.AppendFormat("- {0} : {1}", error.PropertyName, error.ErrorMessage);
                        sb.AppendLine();
                    }
                }

                return Json(new { Success = false, Message = sb.ToString() });
            }

        }

        // GET: Checklists/Edit/5
        public ActionResult Edit(int? id)
        {
            User user = (User)Session["User"];

            if (user == null)
                return RedirectToAction("Login", "Users");

            if (!user.UserRoles[0].int_LpaRole.bit_ManageChecklist)
                return RedirectToAction("NoPermission", "Home", new { module = "Checklists Managment" });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var users = db.Users.Find(user.int_IdUser);
            Checklist checklist = db.Checklists.SingleOrDefault(x => x.int_IdList == id);

            if (checklist == null)
            {
                return HttpNotFound();
            }
            //checklist.id_Period = checklist.int_Period.int_IdPeriod;
            //ViewBag.Periods = GetPeriods(checklist.int_Period.chr_RepeatPeriod);
            //ViewBag.Days = GetDays();
            //ViewBag.Users = GetUsersDropDown(checklist.UsersChecklists);
            //ViewBag.Areas = GetAreas(-1);
            return View(checklist);
        }

        // POST: Checklists/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit([Bind(Include = "int_IdList,chr_Clave,chr_Name,chr_Description,bit_Activo, Days, SelectedPeriod, SelectedUsers,int_Area, id_Period")] Checklist checklist)
        {
            //if (checklist.SelectedUsers == null)
            //    ModelState.AddModelError(string.Empty, "You have to choose at least one user to answer this checklist.");

            //if (checklist.Days == null)
            //    ModelState.AddModelError(string.Empty, "Select at least one day from the week.");

            //if (checklist.SelectedPeriod == null)
            //    ModelState.AddModelError(string.Empty, "Select the period for the checklist.");

            if (ModelState.IsValid)
            {
                try
                {
                    //var result = db.UsersChecklists.Where(x => x.Checklist.int_IdList == checklist.int_IdList).ToList();

                    //foreach (var userChecklist in result)
                    //    db.UsersChecklists.Remove(userChecklist);

                    //foreach (var item in checklist.SelectedUsers)
                    //{
                    //    db.UsersChecklists.Add(new UsersChecklist()
                    //    {
                    //        Checklist = checklist,
                    //        User = db.Users.Find(item)
                    //    });
                    //}
                    //var period = db.Periods.Find(checklist.id_Period);

                    //period.bit_Sun = FindSelectedDay(checklist.Days, "su");

LayoutProcessAdmin/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LayoutProcessAdmin.Models;
using LayoutProcessAdmin.Models.Checking;

namespace LayoutProcessAdmin.Controllers
{
    public class QuestionsController : Controller
    {
        private LayoutProcessContext db = new LayoutProcessContext();

        // GET: Questions
        [HttpGet]
        public JsonResult Get(int id)
        {
            var questions = db.Questions.Where(x => x.int_Checklist.int_IdList == id).ToList();
            return Json(questions, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> GetQuestion(int id)
        {
            try
            {
                var question = db.Questions.Find(id);
                var answers = await db.Answers.Where(x => x.int_Question.int_IdQuestion == question.int_IdQuestion).Select(i => new { i.chr_Description, i.chr_Variable, i.int_IdAnswer, i.dbl_LowerLimit, i.dbl_UpperLimit }).ToListAsync();
                return Json(new { Success = true, Quest = question, Answs = answers }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { Success = false, Message = e.ToString() }, JsonRequestBehavior.AllowGet);
            }
            
        }

        [HttpGet]
        public async Task<JsonResult> GetQuestions(int id)
        {
            var questions = await db.Questions.Include(x => x.Answers).Where(x => x.int_Checklist.int_IdList == id).ToListAsync();

            foreach (var question in questions)
                foreach (var answer in question.Answers)
                    answer.int_Question = null;

            return Json(new { success = true, data = questions }, JsonRequestBehavior.AllowGet);
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create(string description, string type, bool singleAnswer, string formula, int id_checklist, int id_question)
        {
            try
            {
                if(id_question == -1)
                {
                    var newQuestion = db.Questions.Add(new Question()
                    {
                        bit_SingleAnswer = singleAnswer,
                        chr_Description = description,
                        chr_Type = type,
                        chr_Formula = formula,
                        int_Checklist = db.Checklists.Find(id_checklist)
                    });

                    db.SaveChanges();

                    return Json(new { Success = true, id = newQuestion.int_IdQuestion }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var editQuestion = db.Questions.Include(x => x.Answers).SingleOrDefault(x => x.int_IdQuestion == id_question);
                    editQuestion.chr_Description = description;
                    editQuestion.chr_Type = type;
                    editQuestion.bit_SingleAnswer = singleAnswer;
                    editQuestion.chr_Formula = formula;

                    while (editQuestion.Answers.Count > 0)
                        db.Answers.Remove(editQuestion.Answers[0]);

                    db.Entry(editQuestion).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { Success = true, id = id_question }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { Success = false, Message = e.ToString() });
            }
            
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "int_IdQuestion,chr_Description,chr_Type,bit_SingleAnswer")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> DeleteConfirmed(int id)
        {
            try
            {
                Question question = await db.Questions.Include(v => v.Answers).SingleOrDefaultAsync(v => v.int_IdQuestion == id);

                while (question.Answers.Count > 0)
                    db.Answers.Remove(question.Answers[0]);

                db.Questions.Remove(question);
                db.SaveChanges();
                return Json(new { Success = true });
            }
            catch (Exception e)
            {
                return Json(new { Success = false, Message = e.ToString() });
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LayoutProcessAdmin/Views/Checklists/Attend.cshtml
@model LayoutProcessAdmin.Models.Calendar.Event

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{
    <style type="text/css">
        .custom-textarea {
            width: 100%;
            height: 15vh;
            resize: none;
        }
    </style>

}

<div class="row">
    <div class="col-xl-12">
        <div class="breadcrumb-holder">
            <h1 class="main-title float-left">Answering a Checklist</h1>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item">Checklist</li>
                <li class="breadcrumb-item active">Answer</li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-10 col-xl-10 offset-lg-1 offset-xl-1 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">
                    <div class="row text-success">
                        <h4><i class="fa fa-tasks"></i> </h4>&nbsp;<h4 id="title"></h4>
                    </div>
                </div>
                <p id="description" class="text-justify"></p>
            </div>
            <div class="card-body">
                <div class="col-12" id="questions">
                </div>
            </div>
            <div class="card-footer">
                <div class="row float-right">
                    <a href="@Url.Action("Index", "Home")" class="btn btn-success text-light">Finish <i class="fa fa-check"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
    {

    <script src="~/Scripts/LpaScripts/generate-checklistForm-1.0.0.js"></script>

    <script>
        var eventId = @Model.int_IdEvent;
        var auditConfig = @Model.AuditConfig.int_IdAuditConfig;
        var checklistId;

        $(document).ready(function () {
            GetChecklist(auditConfig);
        });

        function GetChecklistQuestions(id)
        {
            $.ajax({
                url: '@Url.Action("GetQuestions", "Questions")',
                type: 'GET',
                data: { id: id },
                success: function (result) {
                    console.log(result);
                    result.data.forEach(function (e) {
                        $('#questions').append(lpaForm.Question(e.chr_Description, e.chr_Type, e.Answers, e.bit_SingleAnswer, e.chr_Formula));

                        var hr = document.createElement('hr');
                        $('#questions').append(hr);
                    });
                },
                error: function (data) {
                    alert(data);
                }
            });
        }

        function GetChecklist(id)
        {
            $.ajax({
                url: '@Url.Action("GetChecklist", "Checklists")',
                type: 'GET',
                data: { id: id },
                success: function (data) {

                    if (data.success) {
                        var result = data.data;
                        $('#title').html(result.chr_Clave);
                        $('#description').html(result.chr_Description);

                        checklistId = result.int_IdList;

                        GetChecklistQuestions(checklistId);
                    }

                },
                error: function (data) {
                    alert(data);
                }
            });
        }

    </script>

}

LayoutProcessAdmin/Views/Checklists/Delete.cshtml
@model LayoutProcessAdmin.Models.Checking.Checklist

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Checklist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.chr_Clave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chr_Clave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chr_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chr_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chr_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chr_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bit_Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bit_Activo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LayoutProcessAdmin/Views/Checklists/Index.cshtml
@model IEnumerable<LayoutProcessAdmin.Models.Checking.Checklist>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{
    <link href="~/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
}

<div class="row">
    <div class="col-xl-12">
        <div class="breadcrumb-holder">
            <h1 class="main-title float-left">My Checklists</h1>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item">checklists</li>
                <li class="breadcrumb-item active">Index</li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>



<div class="card">
    <div class="card-header">
        @Html.ActionLink("Create Checklist", "Create", null, new { role = "button", @class = "btn btn-success" })
    </div>
    <div class="card-body">
        <table class="table table-bordered table-striped" id="UsersTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>
                        @Html.DisplayNameFor(model => model.chr_Clave)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.chr_Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.chr_Description)
                    </th>
                    <th>
                        Questions Count
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.int_IdList
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.chr_Clave)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.chr_Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.chr_Description)
                        </td>
                        <td>
                            @item.Questions.Count
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-12 col-md-12 col-sm-12 col-lg-12 col-xl-4">
                                    <a href="@Url.Action("Edit", "Checklists", new { id = item.int_IdList })" role="button" class="btn btn-warning btn-sm"><i class="fa fa-pen"></i></a>
                                </div>
                                <div class="col-12 col-md-12 col-sm-12 col-lg-12 col-xl-4">
                                    <a href="@Url.Action("Attend", "Checklists", new { id = item.int_IdList})" role="button" class="btn btn-primary btn-sm disabled"><i class="fa fa-info-circle"></i></a>
                                </div>
                                <div class="col-12 col-md-12 col-sm-12 col-lg-12 col-xl-4">
                                    <a href="#" role="button" class="btn btn-danger btn-sm" onclick="ShowDeleteModal('@item.int_IdList', '@item.chr_Name', '@item.chr_Description')"><i class="fa fa-minus-circle"></i></a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"> <i class="fa fa-question-circle"></i> Are you sure you want to delete this?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Checklist: <span id="lblUsername"></span></h5>
                <h5>Description: </h5><span id="lblEmail"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>

                @using (Html.BeginForm("Delete", "Checklists", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.TextBox("id", "id", new { Hidden = "hidden" })
                    <button type="submit" class="btn btn-danger">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables/dataTables.bootstrap4.min.js"></script>
    <script>

        function ShowDeleteModal(id, userName, email) {
            $('#deleteModal .modal-body #lblUsername').html(" " + userName);
            $('#deleteModal .modal-body #lblEmail').html(" " + email);
            $('#deleteModal .modal-footer #id').val(id);
            $('#deleteModal').modal('show');
        }

        $(document).ready(function () {
            $('#UsersTable').DataTable({
                "scrollY": "400px"
            });
        });
        
    </script>
}